# Generated by Django 5.1.4 on 2025-01-10 02:53

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "published": "Posts that all can access",
        "draft": "Postss only accessible to the author",
        "archived": "Posts that only logged in users can access"
    }
    Status = apps.get_model("posts", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status_post_status'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
